"""Subclass of PaSetting, which is generated by wxFormBuilder."""

import wx
import Recording_GUI

# Implementing PaSetting
class ITRC Recording_GUIPaSetting( Recording_GUI.PaSetting ):
	def __init__( self, parent ):
		Recording_GUI.PaSetting.__init__( self, parent )
	
