"""Subclass of Settings, which is generated by wxFormBuilder."""

import wx
import Recording_GUI

# Implementing Settings
class Settings( Recording_GUI.Settings ):
	def __init__( self, parent ):
		Recording_GUI.Settings.__init__( self, parent )
	
