"""Subclass of WrongPa, which is generated by wxFormBuilder."""

import wx
import Recording_GUI

# Implementing WrongPa
class WrongPa( Recording_GUI.WrongPa ):
	def __init__( self, parent ):
		Recording_GUI.WrongPa.__init__( self, parent )
	
